---
- name: Install Centos SCL
  yum:
    name: centos-release-scl
    state: present
  become: yes
- name: Install Python
  yum:
    name: rh-python36
    state: present
  become: yes
- name: Install Git
  yum:
    name: git
    state: latest
  become: yes
- name: Install Zabbix Repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
    state: present
  become: yes
- name: Install Zabbix Agent
  yum:
    name: zabbix-agent
    state: present
  become: yes
- name: Copy Zabbix Config File
  template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  become: yes
- name: Open Zabbix Agent In firewall
  firewalld:
    service: zabbix-agent
    permanent: yes
    zone: public
    immediate: yes
    state: enabled
  become: yes
- name: Start and Enable Zabbix-Agent
  systemd:
    state: started 
    enabled: yes
    name: zabbix-agent
  become: yes
- name: Make Home Zabbix Directory
  file:
    path: /var/lib/zabbix
    state: directory
    owner: zabbix
    group: root
    mode: 0755
  become: yes
- name: Install Python Scripts
  git: 
    repo: "{{python_scripts_repo}}"
    dest: /var/lib/zabbix
    clone: yes
    update: yes
  become: yes
- name: Set Proper Permissions for Python Scripts
  file:
    dest: /var/lib/zabbix
    owner: zabbix
    group: root
    mode: 0755
    recurse: yes
  become: yes
